// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package stringapi

import (
	"bufio"
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
	"net"
)

type RandomIn struct{}
type RandomOut struct {
	Output string `json:"output"`
}

// RandomCall is an in-progress org.example.string.Random call.
//
// A reply may be sent with Reply or CloseWithReply instead of returning it
// from the Backend method, for instance to hijack the connection afterwards.
type RandomCall struct {
	*govarlink.ServerCall
	Request *govarlink.ServerRequest
}

// Reply sends a non-final reply.
func (call *RandomCall) Reply(out *RandomOut) error {
	return call.ServerCall.Reply(out)
}

// CloseWithReply sends a final reply and closes the call.
func (call *RandomCall) CloseWithReply(out *RandomOut) error {
	return call.ServerCall.CloseWithReply(out)
}

type RepeatIn struct {
	Input string `json:"input"`
}
type RepeatOut struct {
	Output string `json:"output"`
}

// RepeatCall is an in-progress org.example.string.Repeat call.
//
// A reply may be sent with Reply or CloseWithReply instead of returning it
// from the Backend method, for instance to hijack the connection afterwards.
type RepeatCall struct {
	*govarlink.ServerCall
	Request *govarlink.ServerRequest
}

// Reply sends a non-final reply.
func (call *RepeatCall) Reply(out *RepeatOut) error {
	return call.ServerCall.Reply(out)
}

// CloseWithReply sends a final reply and closes the call.
func (call *RepeatCall) CloseWithReply(out *RepeatOut) error {
	return call.ServerCall.CloseWithReply(out)
}

type ReverseIn struct {
	Input string `json:"input"`
}
type ReverseOut struct {
	Output string `json:"output"`
}

// ReverseCall is an in-progress org.example.string.Reverse call.
//
// A reply may be sent with Reply or CloseWithReply instead of returning it
// from the Backend method, for instance to hijack the connection afterwards.
type ReverseCall struct {
	*govarlink.ServerCall
	Request *govarlink.ServerRequest
}

// Reply sends a non-final reply.
func (call *ReverseCall) Reply(out *ReverseOut) error {
	return call.ServerCall.Reply(out)
}

// CloseWithReply sends a final reply and closes the call.
func (call *ReverseCall) CloseWithReply(out *ReverseOut) error {
	return call.ServerCall.CloseWithReply(out)
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) Random(in *RandomIn) (*RandomOut, error) {
	if in == nil {
		in = new(RandomIn)
	}
	out := new(RandomOut)
	err := c.Client.Do("org.example.string.Random", in, out)
	return out, unmarshalError(err)
}

// RandomUpgrade calls org.example.string.Random, requesting the
// connection to be upgraded.
//
// The service must take over the connection: if it replies without doing so,
// the connection is closed. On success the caller owns the connection and must
// close it, and must read from the returned bufio.Reader.
func (c Client) RandomUpgrade(in *RandomIn) (*RandomOut, net.Conn, *bufio.Reader, error) {
	if in == nil {
		in = new(RandomIn)
	}
	out := new(RandomOut)
	conn, br, err := c.Client.DoUpgrade("org.example.string.Random", in, out)
	return out, conn, br, unmarshalError(err)
}
func (c Client) Repeat(in *RepeatIn) (*RepeatOut, error) {
	if in == nil {
		in = new(RepeatIn)
	}
	out := new(RepeatOut)
	err := c.Client.Do("org.example.string.Repeat", in, out)
	return out, unmarshalError(err)
}

// RepeatUpgrade calls org.example.string.Repeat, requesting the
// connection to be upgraded.
//
// The service must take over the connection: if it replies without doing so,
// the connection is closed. On success the caller owns the connection and must
// close it, and must read from the returned bufio.Reader.
func (c Client) RepeatUpgrade(in *RepeatIn) (*RepeatOut, net.Conn, *bufio.Reader, error) {
	if in == nil {
		in = new(RepeatIn)
	}
	out := new(RepeatOut)
	conn, br, err := c.Client.DoUpgrade("org.example.string.Repeat", in, out)
	return out, conn, br, unmarshalError(err)
}
func (c Client) Reverse(in *ReverseIn) (*ReverseOut, error) {
	if in == nil {
		in = new(ReverseIn)
	}
	out := new(ReverseOut)
	err := c.Client.Do("org.example.string.Reverse", in, out)
	return out, unmarshalError(err)
}

// ReverseUpgrade calls org.example.string.Reverse, requesting the
// connection to be upgraded.
//
// The service must take over the connection: if it replies without doing so,
// the connection is closed. On success the caller owns the connection and must
// close it, and must read from the returned bufio.Reader.
func (c Client) ReverseUpgrade(in *ReverseIn) (*ReverseOut, net.Conn, *bufio.Reader, error) {
	if in == nil {
		in = new(ReverseIn)
	}
	out := new(ReverseOut)
	conn, br, err := c.Client.DoUpgrade("org.example.string.Reverse", in, out)
	return out, conn, br, unmarshalError(err)
}

// Backend implements the org.example.string Varlink interface.
//
// A method may send the final reply itself via the provided call rather than
// returning it, for instance to hijack the connection. It must then return a nil
// output: the output is ignored, and returning an error after replying drops the
// connection.
type Backend interface {
	Random(*RandomCall, *RandomIn) (*RandomOut, error)
	Repeat(*RepeatCall, *RepeatIn) (*RepeatOut, error)
	Reverse(*ReverseCall, *ReverseIn) (*ReverseOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "org.example.string.Random":
		in := new(RandomIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Random(&RandomCall{ServerCall: call, Request: req}, in)
	case "org.example.string.Repeat":
		in := new(RepeatIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Repeat(&RepeatCall{ServerCall: call, Request: req}, in)
	case "org.example.string.Reverse":
		in := new(ReverseIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Reverse(&ReverseCall{ServerCall: call, Request: req}, in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	if call.Replied() {
		return nil
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "interface org.example.string\n\nmethod Repeat(\n    input: string\n) -> (output: string)\n\nmethod Reverse(\n    input: string\n) -> (output: string)\n\nmethod Random() -> (output: string)\n",
		Name:       "org.example.string",
	}, h)
}
