// Code generated by go-varlink/varlinkgen. DO NOT EDIT.

package calcapi

import (
	"encoding/json"
	govarlink "github.com/emersion/go-varlink"
)

type DivisionByZeroError struct{}

func (err *DivisionByZeroError) Error() string {
	return "varlink call failed: org.example.calc.DivisionByZero"
}

type DivideIn struct {
	A int `json:"a"`
	B int `json:"b"`
}
type DivideOut struct {
	Result int `json:"result"`
}

// DivideCall is an in-progress org.example.calc.Divide call.
//
// A reply may be sent with Reply or CloseWithReply instead of returning it
// from the Backend method, for instance to hijack the connection afterwards.
type DivideCall struct {
	*govarlink.ServerCall
	Request *govarlink.ServerRequest
}

// Reply sends a non-final reply.
func (call *DivideCall) Reply(out *DivideOut) error {
	return call.ServerCall.Reply(out)
}

// CloseWithReply sends a final reply and closes the call.
func (call *DivideCall) CloseWithReply(out *DivideOut) error {
	return call.ServerCall.CloseWithReply(out)
}

type MultiplyIn struct {
	A int `json:"a"`
	B int `json:"b"`
}
type MultiplyOut struct {
	Result int `json:"result"`
}

// MultiplyCall is an in-progress org.example.calc.Multiply call.
//
// A reply may be sent with Reply or CloseWithReply instead of returning it
// from the Backend method, for instance to hijack the connection afterwards.
type MultiplyCall struct {
	*govarlink.ServerCall
	Request *govarlink.ServerRequest
}

// Reply sends a non-final reply.
func (call *MultiplyCall) Reply(out *MultiplyOut) error {
	return call.ServerCall.Reply(out)
}

// CloseWithReply sends a final reply and closes the call.
func (call *MultiplyCall) CloseWithReply(out *MultiplyOut) error {
	return call.ServerCall.CloseWithReply(out)
}

type Client struct {
	*govarlink.Client
}

func unmarshalError(err error) error {
	verr, ok := err.(*govarlink.ClientError)
	if !ok {
		return err
	}
	var v error
	switch verr.Name {
	case "org.example.calc.DivisionByZero":
		v = new(DivisionByZeroError)
	default:
		return err
	}
	if err := json.Unmarshal(verr.Parameters, v); err != nil {
		return err
	}
	return v
}
func (c Client) Divide(in *DivideIn) (*DivideOut, error) {
	if in == nil {
		in = new(DivideIn)
	}
	out := new(DivideOut)
	err := c.Client.Do("org.example.calc.Divide", in, out)
	return out, unmarshalError(err)
}
func (c Client) Multiply(in *MultiplyIn) (*MultiplyOut, error) {
	if in == nil {
		in = new(MultiplyIn)
	}
	out := new(MultiplyOut)
	err := c.Client.Do("org.example.calc.Multiply", in, out)
	return out, unmarshalError(err)
}

// Backend implements the org.example.calc Varlink interface.
//
// A method may send the final reply itself via the provided call rather than
// returning it, for instance to hijack the connection. It must then return a nil
// output: the output is ignored, and returning an error after replying drops the
// connection.
type Backend interface {
	Divide(*DivideCall, *DivideIn) (*DivideOut, error)
	Multiply(*MultiplyCall, *MultiplyIn) (*MultiplyOut, error)
}

type Handler struct {
	Backend Backend
}

func marshalError(err error) error {
	var name string
	switch err.(type) {
	case *DivisionByZeroError:
		name = "org.example.calc.DivisionByZero"
	default:
		return err
	}
	return &govarlink.ServerError{
		Name:       name,
		Parameters: err,
	}
}
func (h Handler) HandleVarlink(call *govarlink.ServerCall, req *govarlink.ServerRequest) error {
	var (
		out interface{}
		err error
	)
	switch req.Method {
	case "org.example.calc.Divide":
		in := new(DivideIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Divide(&DivideCall{ServerCall: call, Request: req}, in)
	case "org.example.calc.Multiply":
		in := new(MultiplyIn)
		if err := json.Unmarshal(req.Parameters, in); err != nil {
			return err
		}
		out, err = h.Backend.Multiply(&MultiplyCall{ServerCall: call, Request: req}, in)
	default:
		err = &govarlink.ServerError{
			Name:       "org.varlink.service.MethodNotFound",
			Parameters: map[string]string{"method": req.Method},
		}
	}
	if err != nil {
		return marshalError(err)
	}
	if call.Replied() {
		return nil
	}
	return call.CloseWithReply(out)
}

func (h Handler) Register(reg *govarlink.Registry) {
	reg.Add(&govarlink.RegistryInterface{
		Definition: "interface org.example.calc\n\nerror DivisionByZero ()\n\nmethod Multiply(\n    a: int,\n    b: int\n) -> (result: int)\n\nmethod Divide(\n    a: int,\n    b: int\n) -> (result: int)\n",
		Name:       "org.example.calc",
	}, h)
}
